# Package Overview
package_name: bikeshare_model

# Data Files
training_data_file: bike-sharing-dataset.csv

pipeline_name: bikeshare_model
pipeline_save_file: bikeshare_pipeline

# Variables
# The variable we are attempting to predict (Survival)
target: cnt

features:      # final features to be used
  - dteday
  - season
  - hr 
  - holiday 
  - weekday
  - workingday  
  - weathersit   
  - temp
  - atemp
  - hum
  - windspeed
  - casual
  - registered

# Features inside processing pipeline
dteday_var: dteday
weekday_var: weekday
weathersit_var: weathersit
temp_var: temp
atemp_var: atemp
windspeed_var: windspeed
hum_var: hum
yr_var: Year
month_var: Month
holiday_var: holiday
workingday_var: workingday
season_var: season
hr_var: hr

month_mappings:
  January: 0
  February: 1
  March: 2
  April: 3
  May: 4
  June: 5
  July: 6
  August: 7
  September: 8
  October: 9
  November: 10
  December: 11

year_mappings:
  2011: 0
  2012: 1

holiday_mappings:
  No: 0
  Yes: 1

workingday_mappings:
  No: 0
  Yes: 1

season_mappings:
  winter: 0
  fall: 1
  spring: 2
  summer: 3

weathersit_mappings:
  Mist: 0
  Clear: 1
  Light Rain: 2
  Heavy Rain: 3

hour_mappings:
  12am: 0
  1am: 1
  2am: 2
  3am: 3
  4am: 4
  5am: 5
  6am: 6
  7am: 7
  8am: 8
  9am: 9
  10am: 10
  11am: 11
  12pm: 12
  1pm: 13
  2pm: 14
  3pm: 15
  4pm: 16
  5pm: 17
  6pm: 18
  7pm: 19
  8pm: 20
  9pm: 21
  10pm: 22
  11pm: 23

# set train/test split
test_size: 0.20

#Split type
time_based: True
split_var: dteday

# to set the random seed
#random_state: 42

# Regression Model parameters
penalty: 'l1'
alpha: 0.01