name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Depemdencies Format Lint Test
      run: | 
        make all
    
    - name: Build Code to Package
      run: | 
        make build
    - name: Build the Docker image
      run: docker build . -t srivatsadatta777/bikeshare
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: srivatsadatta777
          password: ${{secrets.DOCKERHUBPASS}}
    - name: Deploy Docker images to Docker Hub
      run: docker push srivatsadatta777/bikeshare
    
      
