name: Learning GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Depemdencies
      run: | 
        make install
    
    - name: Format
      run: | 
        make format
    
    - name: test with Pytest
      run: | 
        make test

    - name: lint with Pytest
      run: | 
        make lint
    
      
